language: java

cache:
  directories:
    - $HOME/.m2

after_success:
  - "mvn -Pjavadoc site"
  - "mvn site:stage"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target/staging
  on:
    branch: master 